// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSRepository.Data;

#nullable disable

namespace SSRepository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240805174549_mig-k-05-08-2024")]
    partial class migk05082024
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSRepository.Data.TblAccountDtl", b =>
                {
                    b.Property<long>("PKAccountDtlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PKAccountDtlId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrBal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CurrBalDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKLocationID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OpBal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PKAccountDtlId");

                    b.ToTable("tblAccount_dtl", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblAccountGroupMas", b =>
                {
                    b.Property<long>("PkAccountGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkAccountGroupId"));

                    b.Property<string>("AccountGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkAccountGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NatureOfGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NetCrDrBalanceForRpt")
                        .HasColumnType("bit");

                    b.Property<bool>("PrintDtl")
                        .HasColumnType("bit");

                    b.HasKey("PkAccountGroupId");

                    b.ToTable("tblAccountGroup_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblAccountLicDtl", b =>
                {
                    b.Property<long>("PKAccountLicDtlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PKAccountLicDtlId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidTill")
                        .HasColumnType("datetime2");

                    b.HasKey("PKAccountLicDtlId");

                    b.ToTable("tblAccountLic_dtl", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblAccountLocLnk", b =>
                {
                    b.Property<long>("PKAccountLocLnkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PKAccountLocLnkId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKLocationID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PKAccountLocLnkId");

                    b.ToTable("tblAccountLoc_lnk", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblAccountMas", b =>
                {
                    b.Property<long>("PkAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkAccountId"));

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ApplyCostCenter")
                        .HasColumnType("bit");

                    b.Property<bool?>("ApplyTCS")
                        .HasColumnType("bit");

                    b.Property<bool?>("ApplyTDS")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiscDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dow")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FKBankID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FkAccountGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PrintBrDtl")
                        .HasColumnType("bit");

                    b.Property<string>("Station")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkAccountId");

                    b.ToTable("tblAccount_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblAreaMas", b =>
                {
                    b.Property<long>("PkAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkAreaId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkRegionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkAreaId");

                    b.ToTable("tblArea_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblBrandMas", b =>
                {
                    b.Property<long>("PkBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkBrandId"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkBrandId");

                    b.ToTable("tblBrand_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblCategoryGroupMas", b =>
                {
                    b.Property<long>("PkCategoryGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkCategoryGroupId"));

                    b.Property<string>("CategoryGroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkCategoryGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkCategoryGroupId");

                    b.ToTable("tblCategoryGroup_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblCategorySizeLnk", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkId");

                    b.ToTable("TblCategorySize_lnk", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblCityMas", b =>
                {
                    b.Property<long>("PkCityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkCityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkCityId");

                    b.ToTable("tblCity_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblCountryMas", b =>
                {
                    b.Property<long>("PkCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkCountryId"));

                    b.Property<string>("CapitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkCountryId");

                    b.ToTable("tblCountry_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblDistrictMas", b =>
                {
                    b.Property<long>("PkDistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkDistrictId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkStateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkDistrictId");

                    b.ToTable("tblDistrict_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblLocalityMas", b =>
                {
                    b.Property<long>("PkLocalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkLocalityId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkAreaId")
                        .HasColumnType("bigint");

                    b.Property<string>("LocalityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkLocalityId");

                    b.ToTable("tblLocality_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblLocationMas", b =>
                {
                    b.Property<long>("PkLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkLocationID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FkAccountID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkBranchID")
                        .HasColumnType("bigint");

                    b.Property<int>("FkCityId")
                        .HasColumnType("int");

                    b.Property<long?>("FkLocalityID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkStationID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAllAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllCostCenter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllCustomer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllProduct")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllVendor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBillingLocation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDifferentTax")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkLocationID");

                    b.ToTable("tblLocation_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblProductQTYBarcode", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FKLocationId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkLotID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TranInId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TranInSeriesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TranInSrNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("TranOutId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TranOutSeriesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TranOutSrNo")
                        .HasColumnType("bigint");

                    b.HasKey("PkId");

                    b.ToTable("tblProdQTYBarcode", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblPromotionMas", b =>
                {
                    b.Property<long>("PkPromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkPromotionId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKLocationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKLotID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKProdID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkBrandId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkCustomerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkProdCatgId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkPromotionApplyUnitId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkPromotionProdId")
                        .HasColumnType("bigint");

                    b.Property<string>("FkPromotionUnitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FkReferById")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkVendorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Promotion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PromotionAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PromotionApplyAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionApplyOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PromotionApplyQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionDuring")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PromotionFromDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionFromTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PromotionQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PromotionToDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionToTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkPromotionId");

                    b.ToTable("tblPromotion_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblRegionMas", b =>
                {
                    b.Property<long>("PkRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkRegionId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkZoneId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkRegionId");

                    b.ToTable("tblRegion_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblSalesCrNotedtl", b =>
                {
                    b.Property<long>("FkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FkId"));

                    b.Property<bool?>("AddLT")
                        .HasColumnType("bit");

                    b.Property<string>("Batch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CessAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ChallanSrNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DueQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExciseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExciseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FKChallanID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKChallanSrID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKInvoiceID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKInvoiceSrID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKLinkedProdID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKLocationID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKOrderID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKOrderSrID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKReplID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKReplSrID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKSalesRtnID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKSalesRtnSrID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKSeriesID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkLotId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FreeQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FreeQtyUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GrossAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ICAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ICRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InvoiceSrNo")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LotDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("OrderSrNo")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QtyUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReturnSrNo")
                        .HasColumnType("bigint");

                    b.Property<long>("ReturnTypeID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SCAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SCRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaleRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Scheme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SchemeDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SchemeDiscAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchemeDiscType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SrNo")
                        .HasColumnType("bigint");

                    b.Property<string>("TaxCalcMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TaxableAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAftDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TradeDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TradeDiscAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TradeDiscType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FkId");

                    b.ToTable("tblSalesCrNote_dtl", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblSalesCrNotetrn", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkId"));

                    b.Property<decimal>("AdjAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Cash")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CashAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashDiscType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CashDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashDiscountAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Cheque")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ChequeAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ChequeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChequeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Credit")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CreditAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CreditCard")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CreditCardAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreditCardDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerRegNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DraftMode")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EntryNo")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("EntryTime")
                        .HasColumnType("time");

                    b.Property<decimal>("ExciseAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("FKBankChequeID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKBankCreditCardID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKCarrierID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKPostAccID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKRcptID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKRcptSrID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKSalesPerID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKSeriesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FKTaxID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkPartyId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("FreightAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FreightType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GRDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GRNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ICAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LRDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LRNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LotDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("NoOfCases")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OtherAdjAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PRINT_COUNT")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentDays")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ReverseCharge")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RoundOfDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SchemeDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SgstAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Shipping")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradeDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrnStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkId");

                    b.ToTable("tblSalesCrNote_trn", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblStateMas", b =>
                {
                    b.Property<long>("PkStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkStateId"));

                    b.Property<string>("CapitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkCountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkStateId");

                    b.ToTable("tblState_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblStationMas", b =>
                {
                    b.Property<long>("PkStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkStationId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkDistrictId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkStationId");

                    b.ToTable("tblStation_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblSysDefaults", b =>
                {
                    b.Property<long>("PKSysDefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PKSysDefID"));

                    b.Property<DateTime>("DATE_MODIFIED")
                        .HasColumnType("datetime2");

                    b.Property<string>("FKColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FKTableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("SysDefKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysDefValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKSysDefID");

                    b.ToTable("tblSysDefaults", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblVoucherDtl", b =>
                {
                    b.Property<long>("FkVoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FkVoucherId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKLocationID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKSeriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkaccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkcustomerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FktaxId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkvendorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SrNo")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TaxableAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VoucherAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoucherNarration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FkVoucherId");

                    b.ToTable("tblVoucher_dtl", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblVoucherTrn", b =>
                {
                    b.Property<long>("PkVoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkVoucherId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DraftMode")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EntryNo")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("EntryTime")
                        .HasColumnType("time");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKSeriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PrintCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VoucherAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoucherAmtType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherNarration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkVoucherId");

                    b.ToTable("tblVoucher_trn", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblWalkingCustomerMas", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkLocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("MarriageDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.HasKey("PkId");

                    b.ToTable("tblWalkingCustomer_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblWalletMas", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkId"));

                    b.Property<decimal>("BalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Dr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("FkAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PkId");

                    b.ToTable("tblWallet_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblZoneMas", b =>
                {
                    b.Property<long>("PkZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkZoneId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKCreatedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZoneName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkZoneId");

                    b.ToTable("tblZone_mas", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
