// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSRepository.Data;

#nullable disable

namespace SSRepository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123172333_mig-k-first")]
    partial class migkfirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSRepository.Data.TblBankMas", b =>
                {
                    b.Property<long>("PkBankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkBankId"));

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.HasKey("PkBankId");

                    b.ToTable("tblBank_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblBranchMas", b =>
                {
                    b.Property<long>("PkBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkBranchId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkRegId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkBranchId");

                    b.ToTable("tblBranch_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblCategoryMas", b =>
                {
                    b.Property<long>("PkCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkCategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.HasKey("PkCategoryId");

                    b.ToTable("tblCategory_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblCompany", b =>
                {
                    b.Property<long>("PkCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkCompanyId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("Connection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gstn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkCompanyId");

                    b.ToTable("tblCompany", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblCustomerMas", b =>
                {
                    b.Property<long>("PkCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkCustomerId"));

                    b.Property<string>("Aadhar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharCardBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharCardFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gstno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsAadharVerify")
                        .HasColumnType("int");

                    b.Property<int?>("IsPanVerify")
                        .HasColumnType("int");

                    b.Property<string>("Marital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("PanCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Panno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("PkCustomerId");

                    b.ToTable("tblCustomer_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblEmployeeMas", b =>
                {
                    b.Property<long>("PkEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkEmployeeId"));

                    b.Property<string>("Aadhar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharCardBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharCardFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gstno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsAadharVerify")
                        .HasColumnType("int");

                    b.Property<int?>("IsPanVerify")
                        .HasColumnType("int");

                    b.Property<string>("Marital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("PanCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Panno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("PkEmployeeId");

                    b.ToTable("tblEmployee_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblFormMas", b =>
                {
                    b.Property<long>("PkFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkFormId"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FkMasterFormId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkFormId");

                    b.ToTable("tblForm_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblGridStructer", b =>
                {
                    b.Property<long>("PkGridId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkGridId"));

                    b.Property<long>("FkFormId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkGridId");

                    b.ToTable("tblGridStructer", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblProductMas", b =>
                {
                    b.Property<long>("PkProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkProductId"));

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BoxSize")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseLot")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DistributionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("FKTaxID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkprodCatgId")
                        .HasColumnType("bigint");

                    b.Property<string>("HSNCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KeepStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxStock")
                        .HasColumnType("int");

                    b.Property<int>("MinDays")
                        .HasColumnType("int");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("NameToDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameToPrint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdConv1")
                        .HasColumnType("int");

                    b.Property<int>("ProdConv2")
                        .HasColumnType("int");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchaseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaleRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShelfID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeDisc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TradeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkProductId");

                    b.ToTable("tblProduct_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblSalesOrderdtl", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkId"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKSeriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkLotId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FreeQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ICAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ICRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LotDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SCAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SCRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SchemeDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SchemeDiscAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchemeDiscType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<decimal>("TradeDisc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradeDiscAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TradeDiscType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sno")
                        .HasColumnType("int");

                    b.HasKey("PkId");

                    b.ToTable("tblSalesOrder_dtl", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblSalesOrdertrn", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkId"));

                    b.Property<bool>("Cash")
                        .HasColumnType("bit");

                    b.Property<decimal>("CashAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashDiscType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CashDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashDiscountAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Cheque")
                        .HasColumnType("bit");

                    b.Property<decimal>("ChequeAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ChequeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChequeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Credit")
                        .HasColumnType("bit");

                    b.Property<decimal>("CreditAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EntryNo")
                        .HasColumnType("bigint");

                    b.Property<long>("FKBankChequeID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKSeriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("FkPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GRDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GRNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoundOfDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SgstAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<string>("Statu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TranAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkId");

                    b.ToTable("tblSalesOrder_trn", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblSeriesMas", b =>
                {
                    b.Property<long>("PkSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkSeriesId"));

                    b.Property<bool>("AllowFreeQty")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowWalkIn")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowZeroRate")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoApplyPromo")
                        .HasColumnType("bit");

                    b.Property<string>("BillingRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DefaultQty")
                        .HasColumnType("bit");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkBranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("FormatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetNoFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RoundOff")
                        .HasColumnType("bit");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SeriesNo")
                        .HasColumnType("bigint");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<string>("TranAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkSeriesId");

                    b.ToTable("tblSeries_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblUserMas", b =>
                {
                    b.Property<long>("PkUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkUserId"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirePwddt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expiredt")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkBranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("FkEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkRegId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkRoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Usertype")
                        .HasColumnType("int");

                    b.HasKey("PkUserId");

                    b.ToTable("tblUser_mas", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblVendorMas", b =>
                {
                    b.Property<long>("PkVendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkVendorId"));

                    b.Property<string>("Aadhar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharCardBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharCardFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gstno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsAadharVerify")
                        .HasColumnType("int");

                    b.Property<int?>("IsPanVerify")
                        .HasColumnType("int");

                    b.Property<string>("Marital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("PanCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Panno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("PkVendorId");

                    b.ToTable("tblVendor_mas", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
