// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSRepository.Data;

#nullable disable

namespace SSRepository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240221153705_mig-k-five")]
    partial class migkfive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSRepository.Data.TblProdLotDtl", b =>
                {
                    b.Property<long>("PkLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkLotId"));

                    b.Property<bool>("AddLT")
                        .HasColumnType("bit");

                    b.Property<long?>("Barcode")
                        .HasColumnType("bigint");

                    b.Property<string>("Batch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DistributionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKProdID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FkmfgGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("InTrnFKSeriesID")
                        .HasColumnType("bigint");

                    b.Property<long>("InTrnId")
                        .HasColumnType("bigint");

                    b.Property<long>("InTrnsno")
                        .HasColumnType("bigint");

                    b.Property<string>("LotAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LtExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MRPSaleRateUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MfgDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PKLotId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ProdConv1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PurchaseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PurchaseRateUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaleRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.Property<decimal?>("TradeRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PkLotId");

                    b.ToTable("tblProdLot_dtl", "dbo");
                });

            modelBuilder.Entity("SSRepository.Data.TblProdStockDtl", b =>
                {
                    b.Property<long>("PkStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PkStockId"));

                    b.Property<decimal>("CurStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<long>("FKLocationID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKLotID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKProdID")
                        .HasColumnType("bigint");

                    b.Property<long>("FKUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PKStockId")
                        .HasColumnType("bigint");

                    b.Property<int>("Src")
                        .HasColumnType("int");

                    b.HasKey("PkStockId");

                    b.ToTable("tblProdStock_dtl", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
